[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "Refined_Thermal_FEA_Additive"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [    
    "numpy",
    "scipy",
    "scikit-spatial",
    "matplotlib",
    "joblib",
    ]

# Packages live in src/
[tool.setuptools.packages.find]
where = ["src"]
