#This file is used to create the main class of this module and import methods from different files in this module

import os
import shutil
from .utils import *

from .layer_class import my_layer

class Abaqus_PBF_micro_thermal_class:
#Class for running a single Abaqus PBF simulation

    def __init__(self,input_file_path): #Path of input file
        self.input_file_path = os.getcwd() + "/" + input_file_path 
        self.module_path =  os.path.dirname(os.path.realpath(__file__)) #path to directory of this script
        self.input_file_dict = self.read_input_file() #Read json input file and save as dict
        self.eps = 1e-9 #very small number for rounding errors

    #import methods from other files:
    from .Generate_scanpath_from_mtt import Generate_scanpath
    from .Generate_Step_files_for_layer import Generate_Step_files_for_layer
    
    def run(self):
        # Create output data folder if it does not exist and change directory there:
        if not os.path.exists(self.input_file_dict["output_path"]):
            os.mkdir(self.input_file_dict["output_path"])
        os.chdir(self.input_file_dict["output_path"])

        # make copy of input file and put it in the data folder:
        shutil.copy(self.input_file_path,"./input_file.json")


        print("Starting Abaqus PBF Simulation: " + self.input_file_path)

        #Generate meshes using Abaqus python:
        print("Generating meshes using Abaqus python...")
        os.system(f'abaqus cae noGUI={self.module_path}/Set_up_adaptive_mesh_refinement.py')
        print("Meshes generated!")

        #Read necessary data generated by Abaqus python:
        self.meshing_generated_data_dict = utils.read_json_file("./jsonData.json")

        #Generate event series scanpath for all layers:
        print("Generating scanpath from mtt file: "+self.input_file_dict["AM_build_file"])
        self.Generate_scanpath()
        print("Scanpath generated!")

        #Set up default INP with right directory:
        f = open(f"{self.module_path}/INP_default.inp","r")
        text = f.read()
        text = text.replace("../src",self.module_path)
        f.close()

        f = open("./INP_default.inp","w")
        f.write(text)
        f.close()

        i=0
        #Run simulation of each layer:
        for layer in self.layer_objects_array: #This array of my_layer objects is generated in Generate_scanpath_from_mtt.py

            #Generate step files:
            self.Generate_Step_files_for_layer(layer)
            #Set event series files for this layer:
            self.set_event_series_files(layer)
            #Creates INP of mesh called assembly.inp to be input in the main imp file:
            self.Create_Assembly_INP(layer)
            
            #Run Abaqus for each layer:
            Job_name = f"Job-layer-{layer.number}"

            if layer.number != 1:
                self.add_mesh_to_mesh_solution_mapping(layer) #Add mesh to mesh solution mapping if not layer 1
                shutil.copy("./INP_w_mapping.inp",Job_name+".inp")
            else:
                shutil.copy(f"./INP_default.inp",Job_name+".inp")

            os.system(f"abaqus job={Job_name} cpus=4 interactive ask_delete=OFF")

            # if i == 0:
            #     break #Only run one layer for now
            i+=2

    def set_event_series_files(self,layer):
        os.replace(f"Heat_Series_ly{layer.number}.csv","Event_series_Heat_mm.inp")
        os.replace(f"Roller_Series_ly{layer.number}.csv","Event_series_Roller_mm.inp")
     
    def Create_Assembly_INP(self,layer):
        f = open(f"layer-{layer.number}.inp", "r")
        string = f.read()
        inp_text = string.split("*End Assembly")
        f.close()
        
        f = open('current-layer-Assembly.inp', 'w')
        f.write(inp_text[0])
        f.close()

    def add_mesh_to_mesh_solution_mapping(self,layer):
        f = open("./INP_default.inp", "r")
        text = f.read()
        text = text.replace("***Initial Conditions, type=TEMPERATURE, file=.\Job-layer-2.odb, INTERPOLATE",f"*Initial Conditions, type=TEMPERATURE, file=.\Job-layer-{layer.number-1}.odb, INTERPOLATE")
        f.close()

        f = open(f"INP_w_mapping.inp", "w")
        f.write(text)
        f.close()

    def read_input_file(self):
        os.chdir(self.module_path)
        return(utils.read_json_file(self.input_file_path))
    

