import json
import os
import utils

class Abaqus_PBF:
#Class for running a single Abaqus PBF simulation

    def __init__(self,input_file_path):
        self.input_file_path = input_file_path
        self.input_file_dict = self.read_input_file()

    #import methods from other files:
    from Generate_scanpath_from_mtt import Generate_scanpath
    
    def run(self):
        # Create output folder if it does not exist and change directory there:
        if not os.path.exists(self.input_file_dict["output_path"]):
            os.mkdir(self.input_file_dict["output_path"])
        os.chdir(self.input_file_dict["output_path"])
        

        # Change Directory to specified out path:
        print("Starting Abaqus PBF Simulation: " + self.input_file_path)

        #Generate meshes using Abaqus python:
        print("Generating meshes using Abaqus python...")
        os.system('abaqus cae noGUI=../src/Set_up_adaptive_mesh_refinement.py')
        print("Meshes generated!")

        #Read necessary data generated by Abaqus python:
        self.meshing_generated_data_dict = utils.read_json_file("./jsonData.json")

        #Generate scanpath:
        print("Generating scanpath from mtt file: "+self.input_file_dict["AM_build_file"])
        self.Generate_scanpath()
        print("Scanpath generated!")

        #Generate INPS

        #Run simulation:
    
    def read_input_file(self):
        os.chdir(os.getcwd())
        return(utils.read_json_file(self.input_file_path))
    

