import os
import shutil
import json
from pathlib import Path
from .utils import *

def run(self):

    #Some functions used only here
    def set_event_series_files(layer_number):

        if self.input_file_dict["scanpath_path"] == "":
            path = self.Output_Path / "scanpath"
        else:
            path = self.scanpath_path

        shutil.copyfile( path / f"Heat_Series_ly{layer_number}.csv", "Event_series_Heat_mm.inp")
        shutil.copyfile( path / f"Roller_Series_ly{layer_number}.csv", "Event_series_Roller_mm.inp")
        
    def Create_Assembly_INP(layer_number):
        f = open(f"layer-{layer_number}.inp", "r")
        string = f.read()
        inp_text = string.split("*End Assembly")
        f.close()
        
        f = open('current-layer-Assembly.inp', 'w')
        f.write(inp_text[0])
        f.close()

    def add_mesh_to_mesh_solution_mapping(layer_number):
        f = open("./INP_default.inp", "r")
        text = f.read()
        text = text.replace("***Initial Conditions, type=TEMPERATURE, file=.\Job-layer-2.odb, INTERPOLATE",f"*Initial Conditions, type=TEMPERATURE, file=.\Job-layer-{layer_number-1}.odb, INTERPOLATE")
        f.close()

        f = open(f"INP_w_mapping.inp", "w")
        f.write(text)
        f.close()

    #main:

    # Create output data folder if it does not exist:
    if not self.Output_Path.exists(): # if output folder does not exit
        os.mkdir(self.Output_Path)

    # make copy of input file and put it in the data folder:
    # this will be used by Abaqus python 2.7 to generate meshes
    # we will also change the paths to absolute paths
    self.input_file_dict["component_geometry_path"] = str(self.component_geometry_path.resolve())

    file = open(self.Output_Path / 'input_file.json', 'w')
    json.dump(self.input_file_dict, file, indent=4, sort_keys=True)
    file.close()

    print("Starting Abaqus PBF Simulation: \n input file: " + str(self.input_file_path) + "\n output folder: " + str(self.Output_Path))

    #Generate meshes using Abaqus python:
    print("Generating meshes using Abaqus python...")
    os.chdir(self.Output_Path) #change directory to output folder before running abaqus python
    os.system(f'abaqus cae noGUI={ str(self.module_path / "Set_up_adaptive_mesh_refinement.py")} ') #run abaqus python
    os.chdir(self.user_path) #change directory back to user directory
    print("Meshes generated!")

   
    #Read necessary data generated by Abaqus python:
    self.meshing_generated_data_dict = read_json_file(self.Output_Path / "jsonData.json")

    #Set up default INP with right directory:
    f = open(self.module_path / "INP_default.inp" , "r")
    text = f.read()
    text = text.replace("../src", str(self.module_path.resolve()) )
    f.close()

    f = open(self.Output_Path / "INP_default.inp","w")
    f.write(text)
    f.close()

    number_of_layers = round( (self.meshing_generated_data_dict["component_dimensions"][2] + self.eps) / self.input_file_dict["layer_thickness"] )

    #Change directory to output folder:
    os.chdir(self.Output_Path)

    print("Running Abaqus Jobs...")
    #Run simulation of each layer:
    for i in range(number_of_layers): #This array of my_layer objects is generated in Generate_scanpath_from_mtt.py
        
        if i==0 or i==1 or i==2 or i== 3 or i==4 or i==5:
            
            layer_number = i + 1

            #Generate step files:
            self.Generate_Step_files_for_layer(layer_number)
            #Set event series files for this layer:
            set_event_series_files(layer_number)
            #Creates INP of mesh called assembly.inp to be input in the main imp file:
            Create_Assembly_INP(layer_number)
            
            #Run Abaqus for each layer:
            Job_name = f"Job-layer-{layer_number}"
            
            if layer_number != 1:
                add_mesh_to_mesh_solution_mapping(layer_number) #Add mesh to mesh solution mapping if not layer 1
                shutil.copy("./INP_w_mapping.inp",Job_name+".inp")
            else:
                shutil.copy(f"./INP_default.inp",Job_name+".inp")

            os.system(f"abaqus job={Job_name} cpus=16 interactive ask_delete=OFF")

    #change directory back to user directory
    os.chdir(self.user_path)

    print("Simulations Completed!!!")
