import os
import shutil
import json
import numpy as np
from pathlib import Path
from .utils import *

def run(self, Generate_meshes = True, from_layer = 1, until_layer = "end"):

    #Some functions used only here
    def set_event_series_files(layer_number):

        if self.input_file_dict["scanpath_folder"] == "":
            path = self.Output_Path / "scanpath"
        else:
            path = self.scanpath_folder

        shutil.copyfile( path / f"Heat_Series_ly{layer_number}.csv", "Event_series_Heat_mm.inp")
        shutil.copyfile( path / f"Roller_Series_ly{layer_number}.csv", "Event_series_Roller_mm.inp")
        
    def Create_Assembly_INP(layer_number):
        f = open(f"layer-{layer_number}.inp", "r")
        string = f.read()
        inp_text = string.split("*End Assembly")
        f.close()

        if os.path.isfile('current-layer-Assembly.inp'):
            os.remove('current-layer-Assembly.inp')
        
        f = open('current-layer-Assembly.inp', 'w')
        f.write(inp_text[0])
        f.close()

    def add_mesh_to_mesh_solution_mapping(layer_number):
        f = open("./INP_default.inp", "r")
        text = f.read()
        text = text.replace("***Initial Conditions, type=TEMPERATURE, file=.\Job-layer-2.odb, INTERPOLATE",f"*Initial Conditions, type=TEMPERATURE, file=Job-layer-{layer_number-1}.odb, INTERPOLATE")
        f.close()

        f = open(f"INP_w_mapping.inp", "w")
        f.write(text)
        f.close()

    def change_power_in_event_series():
        # this function is used to rewrite the event series files with the laser power specified by the user in case it has imported its own scanpath
        
        os.chdir(self.scanpath_folder) 

        for n in range(1, self.number_of_layers + 1):
            # Read CSV file into a NumPy array
            data = np.genfromtxt(f'Heat_Series_ly{n}.csv', delimiter=',')

            power_column = data[:, -1]

            # Change all non-zero values to the laser power specified by the user
            power_column[power_column != 0] = self.input_file_dict["Laser_Power"]

            data[:, -1] = power_column

            np.savetxt(f'Heat_Series_ly{n}.csv', data, delimiter=',')

        os.chdir(self.user_path)

    #main:

    # Create output data folder if it does not exist:
    if not self.Output_Path.exists(): # if output folder does not exit
        os.mkdir(self.Output_Path)

    # make copy of input file and put it in the data folder:
    # this will be used by Abaqus python 2.7 to generate meshes
    # we will also change the paths to absolute paths
    self.input_file_dict["component_geometry_path"] = str(self.component_geometry_path.resolve())

    file = open(self.Output_Path / 'input_file.json', 'w')
    json.dump(self.input_file_dict, file, indent=4, sort_keys=True)
    file.close()

    print("Starting Abaqus PBF Simulation: \n input file: " + str(self.input_file_path) + "\n output folder: " + str(self.Output_Path))

    if Generate_meshes:
        #Generate meshes using Abaqus python:
        print("Generating meshes using Abaqus python...")
        os.chdir(self.Output_Path) #change directory to output folder before running abaqus python
        os.system(f'abaqus cae noGUI={ str(self.module_path / "Set_up_adaptive_mesh_refinement_Abq2020.py")} ') #run abaqus python
        os.chdir(self.user_path) #change directory back to user directory
        print("Meshes generated!")

   
    #Read necessary data generated by Abaqus python:
    self.meshing_generated_data_dict = read_json_file(self.Output_Path / "jsonData.json")

    #Copy INP_default.inp to output folder and change some parameters   :
    f = open(self.module_path / "INP_default.inp" , "r")

    #Set up default INP with right directory:
    text = f.read()
    text = text.replace("../src", str(self.module_path.resolve()) )

    #Change goldak parameters and apsorptivity in INP_default.inp:
    text = text.replace("GOLDAK_PARAMS_SUBS",f"{self.input_file_dict['Goldak_a']}, {self.input_file_dict['Goldak_b']}, {self.input_file_dict['Goldak_cf']}, {self.input_file_dict['Goldak_cr']}, {self.input_file_dict['Goldak_ff']}, {self.input_file_dict['Goldak_fr']}")
    text = text.replace("APSORPTIVITY_SUBS",f"{self.input_file_dict['absorptivity']}")
    f.close()

    f = open(self.Output_Path / "INP_default.inp","w")
    f.write(text)
    f.close()

    self.number_of_layers = round( (self.meshing_generated_data_dict["component_dimensions"][2] + self.eps) / self.input_file_dict["layer_thickness"] ) - 1

    if self.input_file_dict["scanpath_folder"] != "":
        change_power_in_event_series()

    #Change directory to output folder:
    os.chdir(self.Output_Path)

    #Delete .lck files:
    os.system("rm *.lck")

    print("Running Abaqus Jobs...")
    #Run simulation of each layer:

    if until_layer == "end":
        last_layer = self.number_of_layers
    else:
        last_layer = until_layer

    for i in range(from_layer - 1, last_layer): #This array of my_layer objects is generated in Generate_scanpath_from_mtt.py
        
        # if i==4: 
        #     break
            
        layer_number = i + 1

        #Generate step files:
        self.Generate_Step_files_for_layer(layer_number)
        #Set event series files for this layer:
        set_event_series_files(layer_number)
        #Creates INP of mesh called assembly.inp to be input in the main imp file:
        Create_Assembly_INP(layer_number)
        
        #Run Abaqus for each layer:
        Job_name = f"Job-layer-{layer_number}"
        
        if layer_number != 1:
            add_mesh_to_mesh_solution_mapping(layer_number) #Add mesh to mesh solution mapping if not layer 1
            shutil.copy("./INP_w_mapping.inp",Job_name+".inp")
        else:
            shutil.copy(f"./INP_default.inp",Job_name+".inp")

        if self.input_file_dict["run_with_slurm"] == "yes": #run Abaqus with slurm
            f = open(self.module_path / "Run_abaqus_slurm.sh", "r")
            text = f.read()
            text = text.replace("INP",Job_name)
            text = text.replace("$$number_of_tasks",str(self.input_file_dict["cpus"]))
            f.close()

            f = open(f"Run_abaqus_slurm.sh", "w")
            f.write(text)
            f.close()

            os.system(f"sbatch -W Run_abaqus_slurm.sh")

        else:
            os.system(f"abaqus job={Job_name} cpus={self.input_file_dict['cpus']} interactive ask_delete=OFF")

    #change directory back to user directory
    os.chdir(self.user_path)

    print("Simulations Completed!!!")
