import os
import shutil
from .utils import *

def run(self):

    #Some functions used only here
    def set_event_series_files(layer_number):
        os.replace(f"scanpath\Heat_Series_ly{layer_number}.csv","Event_series_Heat_mm.inp")
        os.replace(f"scanpath\Roller_Series_ly{layer_number}.csv","Event_series_Roller_mm.inp")
        
    def Create_Assembly_INP(layer_number):
        f = open(f"layer-{layer_number}.inp", "r")
        string = f.read()
        inp_text = string.split("*End Assembly")
        f.close()
        
        f = open('current-layer-Assembly.inp', 'w')
        f.write(inp_text[0])
        f.close()

    def add_mesh_to_mesh_solution_mapping(layer_number):
        f = open("./INP_default.inp", "r")
        text = f.read()
        text = text.replace("***Initial Conditions, type=TEMPERATURE, file=.\Job-layer-2.odb, INTERPOLATE",f"*Initial Conditions, type=TEMPERATURE, file=.\Job-layer-{layer_number-1}.odb, INTERPOLATE")
        f.close()

        f = open(f"INP_w_mapping.inp", "w")
        f.write(text)
        f.close()

    #main:

    # Create output data folder if it does not exist and change directory there:
    if not os.path.exists(self.input_file_dict["output_path"]):
        os.mkdir(self.input_file_dict["output_path"])
    os.chdir(self.input_file_dict["output_path"])

    # make copy of input file and put it in the data folder:
    shutil.copy(self.input_file_path,"./input_file.json")

    print("Starting Abaqus PBF Simulation: " + self.input_file_path)

    #Generate meshes using Abaqus python:
    print("Generating meshes using Abaqus python...")
    # os.system(f'abaqus cae noGUI={self.module_path}/Set_up_adaptive_mesh_refinement.py')
    print("Meshes generated!")

    #Read necessary data generated by Abaqus python:
    self.meshing_generated_data_dict = read_json_file("./jsonData.json")

    #Set up default INP with right directory:
    f = open(f"{self.module_path}/INP_default.inp","r")
    text = f.read()
    text = text.replace("../src",self.module_path)
    f.close()

    f = open("./INP_default.inp","w")
    f.write(text)
    f.close()

    number_of_layers = round( (self.meshing_generated_data_dict["component_dimensions"][2] + self.eps) / self.input_file_dict["layer_thickness"] )


    #Run simulation of each layer:
    for i in range(number_of_layers): #This array of my_layer objects is generated in Generate_scanpath_from_mtt.py
        
        if i==0 or i==1 or i==2 or i== 3 or i==4 or i==5:
            
            layer_number = i + 1

            #Generate step files:
            self.Generate_Step_files_for_layer(layer_number)
            #Set event series files for this layer:
            set_event_series_files(layer_number)
            #Creates INP of mesh called assembly.inp to be input in the main imp file:
            Create_Assembly_INP(layer_number)
            
            #Run Abaqus for each layer:
            Job_name = f"Job-layer-{layer_number}"
            
            if layer_number != 1:
                add_mesh_to_mesh_solution_mapping(layer_number) #Add mesh to mesh solution mapping if not layer 1
                shutil.copy("./INP_w_mapping.inp",Job_name+".inp")
            else:
                shutil.copy(f"./INP_default.inp",Job_name+".inp")

            os.system(f"abaqus job={Job_name} cpus=16 interactive ask_delete=OFF")

